version: "3.9"
services:
  redis:
    container_name: travel-backend-redis-prod
    image: redis:alpine
    restart: always

  api:
    container_name: travel-backend-api-prod
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "8000:3000"
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGODB_URL=${MONGODB_URL}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ACCESS_EXPIRATION_MINUTES=30
      - JWT_REFRESH_EXPIRATION_DAYS=30
      - JWT_RESET_PASSWORD_EXPIRATION_MINUTES=10
      - JWT_VERIFY_EMAIL_EXPIRATION_MINUTES=10
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - EMAIL_FROM=${EMAIL_FROM}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - STRIPE_SUCCESS_URL=${STRIPE_SUCCESS_URL}
      - STRIPE_CANCEL_URL=${STRIPE_CANCEL_URL}
      - BACKEND_IP=0.0.0.0
      - STORAGE_MODE=${STORAGE_MODE}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - S3_REGION=${S3_REGION}
    depends_on:
      - redis
